### ISSUE TITLE
How do I compile this mod?

### ISSUE THREAD

**Issue by beppe9000** [Kyzderp/AutoCraftMod#2]
Can you instruct me on how to compile this mod on a Windows 10 machine?

**Comment by Kyzderp** [comment]
This is a LiteLoader mod, so if you don't have the environment set up you can follow mumfrey's tutorial [here](https://www.assembla.com/spaces/liteloader/wiki/Tutorial), also making sure to follow the extra instructions in this [README](https://www.assembla.com/spaces/liteloader/subversion/source/HEAD/LiteLoader/trunk/README.md), and after you have that you should be able to compile with a new project, the source files, and possibly some changes. It's been a long while since I've had to start on a fresh mod; most of the time I just copy one of my existing projects and edit it to make a "new" one.

If you are just looking for the compiled .litemod, the latest is [here](http://forums.teamextrememc.com/index.php/topic/35550-kyzderps-autocraft-mod-18/). I haven't been very good about updating the wiki on Github, so that post is where it is and also has a small disclaimer for the update.

**Comment by beppe9000** [comment]
Thanks!
